version: '3'

services:
  alloydemokit:
    image: brianweet/alloydemokit:sql-express
    build:
      context: .\AlloyDemoKit
      dockerfile: Dockerfile
    networks:
      - alloy-network
networks:
  alloy-network:
    external:
      name: nat