version: '3'

services:
  alloydemokit:
    image: brianweet/alloydemokit:v2
    networks:
      - alloy-network
    depends_on:
      - alloydemokit-db
  alloydemokit-db:
    image: brianweet/alloydemokit-db:linux
    networks:
      - alloy-network
networks:
  alloy-network:
    external:
      name: nat